# Generated by Django 5.1.5 on 2025-04-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_knowledgebase_is_embedded'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='widget_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
