# Generated by Django 5.2.1 on 2025-07-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_knowledgebase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
