# Generated by Django 5.1.5 on 2025-04-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_knowledgebase_widget_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='embedded',
            field=models.BooleanField(default=False),
        ),
    ]
