# Generated by Django 5.2.1 on 2025-07-10 06:40

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_knowledgebase_embedded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='knowledge_bases/'),
        ),
    ]
