# Generated by Django 5.2.1 on 2025-07-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_knowledgebase_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(upload_to='knowledge_bases/'),
        ),
    ]
