# Generated by Django 5.2.1 on 2025-07-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_knowledgebase_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="file",
            field=models.FileField(upload_to="knowledge_bases/"),
        ),
        migrations.CreateModel(
            name="FailedLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="The username attempted (if provided).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="The IP address from which the attempt was made.",
                        null=True,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_time", models.DateTimeField(auto_now=True)),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp until which the account/IP is locked.",
                        null=True,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["username"], name="core_failed_usernam_059972_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="core_failed_ip_addr_6e26d5_idx"
                    ),
                ],
                "unique_together": {("username", "ip_address")},
            },
        ),
    ]
