# Generated by Django 5.2.1 on 2025-07-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_knowledgebase_file_failedloginattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FailedLoginAttempt",
        ),
    ]
