# Generated by Django 5.2.1 on 2025-07-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_knowledgebase_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'verbose_name_plural': 'Knowledge Bases'},
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='error_message',
            field=models.TextField(blank=True, help_text='Stores any error messages if embedding fails.', null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', help_text='Current processing status of the knowledge base embeddings.', max_length=20),
        ),
    ]
