# Generated by Django 5.2.1 on 2025-07-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_knowledgebase_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='embedded',
        ),
    ]
