# Generated by Django 5.2.1 on 2025-07-23 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_knowledgebase_embedded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="file",
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="is_embedded",
            field=models.BooleanField(
                default=False,
                help_text="True if this Knowledge Base's embeddings are generated and stored.",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="widget_slug",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="KnowledgeBaseSourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The actual file content for the knowledge base.",
                        upload_to="kb_source_files/",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original filename for display.", max_length=255
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        help_text="The Knowledge Base this file belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_files",
                        to="core.knowledgebase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Knowledge Base Source Files",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
