# Generated by Django 5.2.1 on 2025-07-24 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_knowledgebase_error_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotUsage",
            fields=[
                (
                    "knowledge_base",
                    models.OneToOneField(
                        help_text="The Knowledge Base these usage statistics belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="usage_stats",
                        serialize=False,
                        to="core.knowledgebase",
                    ),
                ),
                (
                    "total_messages_sent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of messages sent to this chatbot.",
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last message sent to this chatbot.",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time these usage statistics were updated.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chatbot Usage Statistics",
            },
        ),
    ]
