steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/chatbot-api-platform/chatbot-api-platform', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/chatbot-api-platform/chatbot-api-platform']


  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - chatbot-api-platform
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/chatbot-api-platform/chatbot-api-platform
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "8000"
      - --memory
      - "1Gi"
    env:
      - 'DJANGO_SETTINGS_MODULE=chatbot_platform.settings.base'  # if using modular settings
      - 'PYTHONUNBUFFERED=1'
      - 'DJANGO_ALLOWED_HOSTS=chatbot-api-platform-29773676777.us-central1.run.app'

timeout: "900s"