services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      gunicorn chatbot_platform.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chatbot_platform.settings.prod
      - key: PYTHON_VERSION
        value: 3.10